import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'welcome': 'Welcome',
          'Whatwant': 'what do\n you want?',
          'collectOrder': '1 - Collect Order',
          'checkHistory': '2 - Check History',
          'Friends': 'Friends',
          'Number Of Friends': 'Number Of Friends',
          'Next': 'Next',
          "Friends' Names": "Friends' Names",
          'Insert friends Name': 'Insert friends Name',
          'User': 'User',
          'Products': 'Products',
          'Insert Products which you want to Buy ...':
              'Insert Products which you want to Buy ...',
          'Remove': 'Remove',
          'Confirm': 'Confirm',
          'Are you sure to delete this product?':
              'Are you sure to delete this product?',
          'DELETE': 'DELETE',
          'CANCEL': 'CANCEL',
          'add another': 'add another',
          'No products added': 'No products added',
          'add product': 'add product',
          'add Products': 'add Products',
          'Please enter product name Ex:Chicken':
              'Please enter product name Ex:Chicken',
          'Name': 'Name',
          'Please enter product price Ex:25.0':
              'Please enter product price Ex:25.0',
          'Price': 'Price',
          'Done': 'Done',
          'Items': 'Items',
          'Total': 'Total',
          'Report': 'Report',
          'Summery Order': 'Summery Order',
          'Per Product': 'Per Product',
          'Quntity': 'Quntity',
          'EGP': 'EGP',
          'Per User': 'Per User',
          'History': 'History',
          'Empty': 'Empty',
          '1- Collect Order': '1- Collect Order',
          '2- No,Thanks': '2- No,Thanks',
          'Are you sure ?': 'Are you sure ?',
          'Order': 'Order',
          'Details': 'Details',
          "Let's Collect Order": "Let's Collect Order",
          "are you want to Erase all data ?\nTo delete specific One swipe Right <-":
              "are you want to Erase all data ?\nTo delete a specific One swipe Right <-",
          "Enter a name": "Enter a name",
          "Friend": "Friend",
          "Currency": "Currency",
          "Language": "Language"
        },
        'ar_EG': {
          'welcome': 'مرحبا',
          'Whatwant': 'ماذا تريد؟',
          'collectOrder': 'جمع اوردر',
          'checkHistory': 'اوردرات سابقة',
          'Friends': 'الاصدقاء',
          'Number Of Friends': 'عدد الاصدقاء',
          'Next': 'التالي',
          "Friends' Names": "اسماء الاصدقاء",
          'Insert friends Name': 'ادخل اسم الشخص',
          'User': 'مستخدم',
          'Products': 'منتجات',
          'Insert Products which you want to Buy ...':
              'ادخل المنتجات المراد شرائها',
          'Remove': 'حذف',
          'Confirm': 'تآكيد',
          'Are you sure to delete this product?': 'هل تريد مسح المنتج؟',
          'DELETE': 'مسح',
          'CANCEL': 'الغاء',
          'add another': 'ادخال اخر',
          'No products added': 'لم يتم ادخال منتج بعد',
          'add product': 'اضافه منتج',
          'add Products': 'اضافه منتجات',
          'Please enter product name Ex:Chicken': 'اسم المنتج :مثال فراخ',
          'Name': 'الاسم',
          'Please enter product price Ex:25.0': 'سعر المنتج : مثال 25',
          'Price': 'السعر',
          'Done': 'تم',
          'Items': 'العدد',
          'Total': 'المجموع',
          'Report': 'التقرير',
          'Summery Order': 'ملخص الاوردر',
          'Per Product': 'لكل منتج',
          'Quntity': 'الكميه',
          'EGP': 'جنيه مصري',
          'Per User': 'لكل مستخدم',
          'History': 'اوردرات سابقه',
          'Empty': 'لا يوجد',
          '1- Collect Order': 'آ - جمع اوردر الان',
          '2- No,Thanks': 'ب - لا شكرا',
          'Are you sure ?': 'هل انت متآكد؟',
          'Order': 'اوردر',
          'Details': 'الوقت',
          "Let's Collect Order": "يلا نجمع اوردر",
          'USD': 'دولار امريكي',
          "are you want to Erase all data ?\nTo delete specific One swipe Right <-":
              "هل انت متاكد من مسح جميع السجلات ؟\nلمسح سجل واحد قم بالسحب عليه من اليسار الي اليمن",
          "Enter a name": "ادخل الاسم",
          "Save": "حفظ",
          "Friend": "صديق",
          "Currency": "العمله",
          "Language": "Language"
        },
        'es_ES': {
          'welcome': 'hola',
          'Whatwant': 'qué quieres?',
          'collectOrder': '1 - Orden de Cobro',
          'checkHistory': '2 - Verificar historial',
          'Friends': 'amigos',
          'Number Of Friends': 'Número de amigos',
          'Next': 'siguiente',
          "Friends' Names": "Nombres de amigos",
          'Insert friends Name': 'Insertar nombre de amigos',
          'User': 'Usuario',
          'Products': 'Productos',
          'Insert Products which you want to Buy ...':
              'nserte Productos que desea Comprar...',
          'Remove': 'Eliminar',
          'Confirm': 'Confirmar',
          'Are you sure to delete this product?':
              'Estás seguro de eliminar este producto?',
          'DELETE': 'ELIMINAR',
          'CANCEL': 'CANCELAR',
          'add another': 'agregar otro',
          'No products added': 'No se agregaron productos',
          'add product': 'agregar otro',
          'add Products': 'agregar producto',
          'Please enter product name Ex:Chicken':
              'Por favor ingrese el nombre del producto Ej: Pollo',
          'Name': 'nombre',
          'Please enter product price Ex:25.0':
              'Ingrese el precio del producto Ej: 25.0',
          'Price': 'Precio',
          'Done': 'hecho',
          'Items': 'Artículos',
          'Total': 'Totales',
          'Report': 'Informe',
          'Summery Order': 'Orden Veraniega',
          'Per Product': 'Por producto',
          'Quntity': 'Cantidad',
          'EGP': 'EGP',
          'Per User': 'Por Usuario',
          'History': 'Historia',
          'Empty': 'Vacío',
          '1- Collect Order': '1- Orden de Cobro',
          '2- No,Thanks': '2- No, gracias',
          'Are you sure ?': 'Estás seguro?',
          'Order': 'orden',
          'Details': 'Detalles',
          "Let's Collect Order": "Recolectemos el pedido",
          "are you want to Erase all data ?\nTo delete specific One swipe Right <-":
              "¿Quieres borrar todos los datos?\nPara eliminar un One específico, deslice el dedo hacia la derecha <-",
          "Save": "Guardar",
          "Friend": "Amiga",
          "Currency": "Moneda",
          "Language": "Lenguaje"
        },
      };
}
